[package]
name = "kbnf-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.4.7"
kbnf = { path = ".." }

[[bin]]
name = "grammar_construction"
path = "fuzz_targets/grammar_construction.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
